fix for PP if you can live with a backdrop
Rhyono/CraftStore pull request #43
Opened 2023-11-12 07:38 UTC by DakJaniels

[https://youtu.be/cJlV2L1wtA4](url)

2023-11-12 23:18 UTC, MuMuQ requested changes

2023-11-12 23:18 UTC, MuMuQ commented on CraftStore.lua
If you add
```ZO_ProvisionerTopLevel:SetHidden(false)``` in line 1913
and 
```ZO_ProvisionerTopLevel:SetHidden(true)``` in line 1923 the backdrop should be gone.

Tested with and without PerfectPixel, both with and without Gamepad mode.

Otherwise your suggested change seems to be doing exactly what is is supposed to do, thank you :)

2023-11-12 23:18 UTC, MuMuQ commented on CraftStore.lua
Seems like I can't make direct code suggestions as a non-maintainer :/

2023-11-13 00:12 UTC, DakJaniels commented on CraftStore.lua
I will edit.

2023-11-13 00:56 UTC, MuMuQ approved these changes
LGTM :)

2023-11-13 04:48 UTC, merged